"""Generate figure3_error_attribution.ipynb from figure3_error_attribution.py.

This keeps the notebook in sync with the script: any edits to the script are
reflected in the notebook by re-running this generator.
"""

import sys
import re
from pathlib import Path

sys.path.insert(0, '/scistor/guest/gbb083/AeroCom/.nb_tools')
import nbformat as nbf

script_path = Path('/scistor/guest/gbb083/AeroCom/notebooks/figure3_error_attribution.py')
out_path = Path('/scistor/guest/gbb083/AeroCom/notebooks/figure3_error_attribution.ipynb')

text = script_path.read_text()

# Top docstring becomes the intro markdown cell
match = re.match(r'"""(.*?)"""', text, re.DOTALL)
intro_md = match.group(1).strip() if match else ''

# Remove the docstring to get the code body
code_text = text[match.end():].strip() if match else text

# Section headers are formatted as 77 dashes with a numbered title
section_pattern = re.compile(r'^(# -{77}\n#\s+(\d+)\.\s+(.*?)\n# -{77})$', re.MULTILINE)
parts = section_pattern.split(code_text)
pre_section = parts[0].strip()

cells = []
if intro_md:
    config_note = (
        "\n\n## Configuration\n\n"
        "- `EXCLUDE_MODELS`: list of model names to drop before any processing (must match pickle keys exactly).\n"
        "- `LIFETIME_MAX_DAYS` / `LIFETIME_MIN_DAYS`: lifetime values outside this range, plus NaN/inf, are masked before aggregation and regressions.\n\n"
        "## Notes and caveats\n\n"
        "- The model monthly pickle is regenerated by `py/get_data.py` in `Data/var_files/original/monthly/`.\n"
        "- This notebook loads from the legacy master pickle by default; set `USE_PICKLE = False` to load from NetCDF files under `Data/AP3_processed_monthly/` instead.\n"
        "- POLDER-GRASP 3-hourly collocated data are aggregated to monthly and then seasonal regional means.\n"
        "- GPCP monthly precipitation is used for observed precipitation.\n"
        "- Model precipitation files have mixed units; a unit-normalization step converts everything to mm day⁻¹ and applies a sanity check for mislabeled g m⁻² s⁻¹ files.\n"
        "- Some models lack `abs550aer` or spectral AOD variables and are excluded from the MAC/SSA/AE regressions.\n"
        "- Lifetime (`load / emission`) can contain very large or non-finite values; a configurable filter removes these before the regression."
    )
    if '## Notes and caveats' in intro_md:
        intro_md = re.sub(r'## Notes and caveats.*', config_note.lstrip(), intro_md, flags=re.DOTALL)
    else:
        intro_md += config_note
    cells.append(nbf.v4.new_markdown_cell(intro_md))

if pre_section:
    cells.append(nbf.v4.new_code_cell(pre_section))

for i in range(1, len(parts), 4):
    if i + 3 >= len(parts):
        break
    title = parts[i + 2].strip()
    content = parts[i + 3].strip()
    cells.append(nbf.v4.new_markdown_cell(f'## {title}'))
    if content:
        cells.append(nbf.v4.new_code_cell(content))

nb = nbf.v4.new_notebook()
nb['cells'] = cells
nb.metadata.kernelspec = {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'}

with open(out_path, 'w') as f:
    nbf.write(nb, f)

print(f'Created notebook: {out_path}')
print(f'Total cells: {len(cells)}')
